name: media-library
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile_mongo
    container_name: media_lib_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: mongod --auth --keyFile /etc/mongo/keyfile --replSet rs0 --bind_ip_all

  minio:
    image: minio/minio:latest
    container_name: media_lib_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: media-library
      MINIO_ROOT_PASSWORD: password
      MINIO_SERVER_URL: http://minio:9000
    command: server /data --console-address ":9001"

volumes:
  mongodb_data:
  minio_data: